export const WELCOME_STEP = 'WELCOME_STEP'
export const ENTER_PIN_STEP = 'ENTER_PIN_STEP'
export const WITHDRAWAL_STEP = 'WITHDRAWAL_STEP'
export const WITHDRAWAL_OTHER_AMOUNT_STEP = 'WITHDRAWAL_OTHER_AMOUNT_STEP'
